services:
  02_1_cache_mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: codely
      MYSQL_PASSWORD: c0d3ly7v
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./databases/ecommerce.sql:/docker-entrypoint-initdb.d/init.sql

  02_1_cache_varnish:
    image: varnish:7.4
    ports:
      - "80:80"
    volumes:
      - ./etc/varnish:/etc/varnish:ro
    command: varnishd -F -f /etc/varnish/default.vcl -s malloc,256m

volumes:
  db_data:
